version: '3.9'

services:
  
  shorter-url-db:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  shorter-url-api:
    build: 
      context: ./app
      target: development
    restart: unless-stopped
    depends_on:
      - shorter-url-db
    env_file:
      - .env
    environment:
      PRODUCTION: "false"
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: shorter-url-db
      POSTGRES_PORT: 5432
    volumes:
      - ./app:/go/src/app
    ports:
      - ${API_PORT}:80
