version: '3.9'

services:
  
  shorter-url-db:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  shorter-url-api:
    build: './app'
    restart: unless-stopped
    depends_on:
      - shorter-url-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: shorter-url-db
      POSTGRES_PORT: 5432
    volumes:
      - ./app:/go/src/app
    ports:
      - "80:80"
